spring:
  application:
    name: k-budget-api
  profiles:
    default: prod

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    access-expiration: 900000
    refresh-expiration: 2592000000
  admin-emails: ${ADMIN_EMAILS:}

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
