// Mocks generated by Mockito 5.4.6 from annotations
// in k_budget/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;

import 'package:k_budget/src/domain/enums/enums.dart' as _i19;
import 'package:k_budget/src/domain/models/account.dart' as _i10;
import 'package:k_budget/src/domain/models/app_config.dart' as _i2;
import 'package:k_budget/src/domain/models/budget.dart' as _i13;
import 'package:k_budget/src/domain/models/budget_history.dart' as _i15;
import 'package:k_budget/src/domain/models/budget_overview.dart' as _i14;
import 'package:k_budget/src/domain/models/category.dart' as _i9;
import 'package:k_budget/src/domain/models/debt.dart' as _i8;
import 'package:k_budget/src/domain/models/debt_payment.dart' as _i24;
import 'package:k_budget/src/domain/models/exchange_rate.dart' as _i12;
import 'package:k_budget/src/domain/models/monthly_summary.dart' as _i21;
import 'package:k_budget/src/domain/models/product.dart' as _i11;
import 'package:k_budget/src/domain/models/recurring_transaction.dart' as _i16;
import 'package:k_budget/src/domain/models/subscription.dart' as _i5;
import 'package:k_budget/src/domain/models/subscription_payment.dart' as _i6;
import 'package:k_budget/src/domain/models/subscription_total_paid.dart' as _i7;
import 'package:k_budget/src/domain/models/transaction.dart' as _i4;
import 'package:k_budget/src/domain/repositories/account_repository.dart'
    as _i26;
import 'package:k_budget/src/domain/repositories/app_config_repository.dart'
    as _i17;
import 'package:k_budget/src/domain/repositories/auth_repository.dart' as _i3;
import 'package:k_budget/src/domain/repositories/budget_repository.dart'
    as _i29;
import 'package:k_budget/src/domain/repositories/category_repository.dart'
    as _i25;
import 'package:k_budget/src/domain/repositories/debt_repository.dart' as _i23;
import 'package:k_budget/src/domain/repositories/exchange_rate_repository.dart'
    as _i28;
import 'package:k_budget/src/domain/repositories/product_repository.dart'
    as _i27;
import 'package:k_budget/src/domain/repositories/recurring_transaction_repository.dart'
    as _i30;
import 'package:k_budget/src/domain/repositories/subscription_repository.dart'
    as _i22;
import 'package:k_budget/src/domain/repositories/transaction_repository.dart'
    as _i20;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppConfig_0 extends _i1.SmartFake implements _i2.AppConfig {
  _FakeAppConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_2 extends _i1.SmartFake implements _i4.Transaction {
  _FakeTransaction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscription_3 extends _i1.SmartFake implements _i5.Subscription {
  _FakeSubscription_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscriptionPayment_4 extends _i1.SmartFake
    implements _i6.SubscriptionPayment {
  _FakeSubscriptionPayment_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscriptionTotalPaid_5 extends _i1.SmartFake
    implements _i7.SubscriptionTotalPaid {
  _FakeSubscriptionTotalPaid_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDebt_6 extends _i1.SmartFake implements _i8.Debt {
  _FakeDebt_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategory_7 extends _i1.SmartFake implements _i9.Category {
  _FakeCategory_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccount_8 extends _i1.SmartFake implements _i10.Account {
  _FakeAccount_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProduct_9 extends _i1.SmartFake implements _i11.Product {
  _FakeProduct_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExchangeRate_10 extends _i1.SmartFake implements _i12.ExchangeRate {
  _FakeExchangeRate_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudget_11 extends _i1.SmartFake implements _i13.Budget {
  _FakeBudget_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudgetOverview_12 extends _i1.SmartFake
    implements _i14.BudgetOverview {
  _FakeBudgetOverview_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudgetHistory_13 extends _i1.SmartFake
    implements _i15.BudgetHistory {
  _FakeBudgetHistory_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecurringTransaction_14 extends _i1.SmartFake
    implements _i16.RecurringTransaction {
  _FakeRecurringTransaction_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfigRepository extends _i1.Mock
    implements _i17.AppConfigRepository {
  @override
  _i18.Future<_i2.AppConfig> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i18.Future<_i2.AppConfig>.value(
              _FakeAppConfig_0(this, Invocation.method(#getConfig, [])),
            ),
            returnValueForMissingStub: _i18.Future<_i2.AppConfig>.value(
              _FakeAppConfig_0(this, Invocation.method(#getConfig, [])),
            ),
          )
          as _i18.Future<_i2.AppConfig>);

  @override
  _i18.Future<void> saveConfig(_i2.AppConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfig, [config]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<bool> isOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#isOnboardingCompleted, []),
            returnValue: _i18.Future<bool>.value(false),
            returnValueForMissingStub: _i18.Future<bool>.value(false),
          )
          as _i18.Future<bool>);

  @override
  _i18.Future<void> setOnboardingCompleted(bool? completed) =>
      (super.noSuchMethod(
            Invocation.method(#setOnboardingCompleted, [completed]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i19.DataMode> getDataMode() =>
      (super.noSuchMethod(
            Invocation.method(#getDataMode, []),
            returnValue: _i18.Future<_i19.DataMode>.value(_i19.DataMode.local),
            returnValueForMissingStub: _i18.Future<_i19.DataMode>.value(
              _i19.DataMode.local,
            ),
          )
          as _i18.Future<_i19.DataMode>);

  @override
  _i18.Future<void> setDataMode(_i19.DataMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setDataMode, [mode]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> setServerUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setServerUrl, [url]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<String?> getServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getServerUrl, []),
            returnValue: _i18.Future<String?>.value(),
            returnValueForMissingStub: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<void> setTheme(_i19.AppTheme? theme) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [theme]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i19.AppTheme> getTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getTheme, []),
            returnValue: _i18.Future<_i19.AppTheme>.value(_i19.AppTheme.light),
            returnValueForMissingStub: _i18.Future<_i19.AppTheme>.value(
              _i19.AppTheme.light,
            ),
          )
          as _i18.Future<_i19.AppTheme>);

  @override
  _i18.Future<void> setTextScale(_i19.TextScale? textScale) =>
      (super.noSuchMethod(
            Invocation.method(#setTextScale, [textScale]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i19.TextScale> getTextScale() =>
      (super.noSuchMethod(
            Invocation.method(#getTextScale, []),
            returnValue: _i18.Future<_i19.TextScale>.value(
              _i19.TextScale.small,
            ),
            returnValueForMissingStub: _i18.Future<_i19.TextScale>.value(
              _i19.TextScale.small,
            ),
          )
          as _i18.Future<_i19.TextScale>);

  @override
  _i18.Future<void> setLockEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setLockEnabled, [enabled]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> setLockMethod(_i19.LockMethod? method) =>
      (super.noSuchMethod(
            Invocation.method(#setLockMethod, [method]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> setHashedPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setHashedPin, [pin]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<List<_i19.Feature>> getEnabledFeatures() =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledFeatures, []),
            returnValue: _i18.Future<List<_i19.Feature>>.value(
              <_i19.Feature>[],
            ),
            returnValueForMissingStub: _i18.Future<List<_i19.Feature>>.value(
              <_i19.Feature>[],
            ),
          )
          as _i18.Future<List<_i19.Feature>>);

  @override
  _i18.Future<void> setEnabledFeatures(List<_i19.Feature>? features) =>
      (super.noSuchMethod(
            Invocation.method(#setEnabledFeatures, [features]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<List<_i19.Feature>> getNavOrder() =>
      (super.noSuchMethod(
            Invocation.method(#getNavOrder, []),
            returnValue: _i18.Future<List<_i19.Feature>>.value(
              <_i19.Feature>[],
            ),
            returnValueForMissingStub: _i18.Future<List<_i19.Feature>>.value(
              <_i19.Feature>[],
            ),
          )
          as _i18.Future<List<_i19.Feature>>);

  @override
  _i18.Future<void> setNavOrder(List<_i19.Feature>? order) =>
      (super.noSuchMethod(
            Invocation.method(#setNavOrder, [order]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i18.Future<_i3.AuthResult> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i18.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i18.Future<_i3.AuthResult>);

  @override
  _i18.Future<_i3.AuthResult> register(
    String? email,
    String? password,
    String? name, {
    String? currency,
    String? timezone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #register,
              [email, password, name],
              {#currency: currency, #timezone: timezone},
            ),
            returnValue: _i18.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(
                  #register,
                  [email, password, name],
                  {#currency: currency, #timezone: timezone},
                ),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(
                  #register,
                  [email, password, name],
                  {#currency: currency, #timezone: timezone},
                ),
              ),
            ),
          )
          as _i18.Future<_i3.AuthResult>);

  @override
  _i18.Future<_i3.AuthResult> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i18.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#refresh, [])),
            ),
            returnValueForMissingStub: _i18.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#refresh, [])),
            ),
          )
          as _i18.Future<_i3.AuthResult>);

  @override
  _i18.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i18.Future<String?>.value(),
            returnValueForMissingStub: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i18.Future<String?>.value(),
            returnValueForMissingStub: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<void> saveTokens(String? accessToken, String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [accessToken, refreshToken]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<bool> hasValidToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasValidToken, []),
            returnValue: _i18.Future<bool>.value(false),
            returnValueForMissingStub: _i18.Future<bool>.value(false),
          )
          as _i18.Future<bool>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i20.TransactionRepository {
  @override
  _i18.Future<List<_i4.Transaction>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i18.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
            returnValueForMissingStub: _i18.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i18.Future<List<_i4.Transaction>>);

  @override
  _i18.Future<List<_i4.Transaction>> getByMonth(int? month, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getByMonth, [month, year]),
            returnValue: _i18.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
            returnValueForMissingStub: _i18.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i18.Future<List<_i4.Transaction>>);

  @override
  _i18.Stream<List<_i4.Transaction>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i18.Stream<List<_i4.Transaction>>.empty(),
            returnValueForMissingStub:
                _i18.Stream<List<_i4.Transaction>>.empty(),
          )
          as _i18.Stream<List<_i4.Transaction>>);

  @override
  _i18.Future<_i4.Transaction> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i18.Future<_i4.Transaction>.value(
              _FakeTransaction_2(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i4.Transaction>.value(
              _FakeTransaction_2(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i18.Future<_i4.Transaction>);

  @override
  _i18.Future<_i4.Transaction> create(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#create, [transaction]),
            returnValue: _i18.Future<_i4.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#create, [transaction]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i4.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#create, [transaction]),
              ),
            ),
          )
          as _i18.Future<_i4.Transaction>);

  @override
  _i18.Future<_i4.Transaction> update(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#update, [transaction]),
            returnValue: _i18.Future<_i4.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#update, [transaction]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i4.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#update, [transaction]),
              ),
            ),
          )
          as _i18.Future<_i4.Transaction>);

  @override
  _i18.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<List<_i21.MonthlySummary>> getMonthlySummary(
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlySummary, [month, year]),
            returnValue: _i18.Future<List<_i21.MonthlySummary>>.value(
              <_i21.MonthlySummary>[],
            ),
            returnValueForMissingStub:
                _i18.Future<List<_i21.MonthlySummary>>.value(
                  <_i21.MonthlySummary>[],
                ),
          )
          as _i18.Future<List<_i21.MonthlySummary>>);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i22.SubscriptionRepository {
  @override
  _i18.Future<List<_i5.Subscription>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i18.Future<List<_i5.Subscription>>.value(
              <_i5.Subscription>[],
            ),
            returnValueForMissingStub:
                _i18.Future<List<_i5.Subscription>>.value(<_i5.Subscription>[]),
          )
          as _i18.Future<List<_i5.Subscription>>);

  @override
  _i18.Stream<List<_i5.Subscription>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i18.Stream<List<_i5.Subscription>>.empty(),
            returnValueForMissingStub:
                _i18.Stream<List<_i5.Subscription>>.empty(),
          )
          as _i18.Stream<List<_i5.Subscription>>);

  @override
  _i18.Future<_i5.Subscription> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i18.Future<_i5.Subscription>.value(
              _FakeSubscription_3(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i5.Subscription>.value(
              _FakeSubscription_3(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i18.Future<_i5.Subscription>);

  @override
  _i18.Future<_i5.Subscription> create(_i5.Subscription? subscription) =>
      (super.noSuchMethod(
            Invocation.method(#create, [subscription]),
            returnValue: _i18.Future<_i5.Subscription>.value(
              _FakeSubscription_3(
                this,
                Invocation.method(#create, [subscription]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i5.Subscription>.value(
              _FakeSubscription_3(
                this,
                Invocation.method(#create, [subscription]),
              ),
            ),
          )
          as _i18.Future<_i5.Subscription>);

  @override
  _i18.Future<_i5.Subscription> update(_i5.Subscription? subscription) =>
      (super.noSuchMethod(
            Invocation.method(#update, [subscription]),
            returnValue: _i18.Future<_i5.Subscription>.value(
              _FakeSubscription_3(
                this,
                Invocation.method(#update, [subscription]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i5.Subscription>.value(
              _FakeSubscription_3(
                this,
                Invocation.method(#update, [subscription]),
              ),
            ),
          )
          as _i18.Future<_i5.Subscription>);

  @override
  _i18.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i6.SubscriptionPayment> pay(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#pay, [id]),
            returnValue: _i18.Future<_i6.SubscriptionPayment>.value(
              _FakeSubscriptionPayment_4(this, Invocation.method(#pay, [id])),
            ),
            returnValueForMissingStub:
                _i18.Future<_i6.SubscriptionPayment>.value(
                  _FakeSubscriptionPayment_4(
                    this,
                    Invocation.method(#pay, [id]),
                  ),
                ),
          )
          as _i18.Future<_i6.SubscriptionPayment>);

  @override
  _i18.Future<List<_i6.SubscriptionPayment>> getPayments(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPayments, [id]),
            returnValue: _i18.Future<List<_i6.SubscriptionPayment>>.value(
              <_i6.SubscriptionPayment>[],
            ),
            returnValueForMissingStub:
                _i18.Future<List<_i6.SubscriptionPayment>>.value(
                  <_i6.SubscriptionPayment>[],
                ),
          )
          as _i18.Future<List<_i6.SubscriptionPayment>>);

  @override
  _i18.Future<_i7.SubscriptionTotalPaid> getTotalPaid(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPaid, [id]),
            returnValue: _i18.Future<_i7.SubscriptionTotalPaid>.value(
              _FakeSubscriptionTotalPaid_5(
                this,
                Invocation.method(#getTotalPaid, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i18.Future<_i7.SubscriptionTotalPaid>.value(
                  _FakeSubscriptionTotalPaid_5(
                    this,
                    Invocation.method(#getTotalPaid, [id]),
                  ),
                ),
          )
          as _i18.Future<_i7.SubscriptionTotalPaid>);
}

/// A class which mocks [DebtRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDebtRepository extends _i1.Mock implements _i23.DebtRepository {
  @override
  _i18.Future<List<_i8.Debt>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i18.Future<List<_i8.Debt>>.value(<_i8.Debt>[]),
            returnValueForMissingStub: _i18.Future<List<_i8.Debt>>.value(
              <_i8.Debt>[],
            ),
          )
          as _i18.Future<List<_i8.Debt>>);

  @override
  _i18.Stream<List<_i8.Debt>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i18.Stream<List<_i8.Debt>>.empty(),
            returnValueForMissingStub: _i18.Stream<List<_i8.Debt>>.empty(),
          )
          as _i18.Stream<List<_i8.Debt>>);

  @override
  _i18.Future<_i8.Debt> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i18.Future<_i8.Debt>);

  @override
  _i18.Future<_i8.Debt> create(_i8.Debt? debt) =>
      (super.noSuchMethod(
            Invocation.method(#create, [debt]),
            returnValue: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(this, Invocation.method(#create, [debt])),
            ),
            returnValueForMissingStub: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(this, Invocation.method(#create, [debt])),
            ),
          )
          as _i18.Future<_i8.Debt>);

  @override
  _i18.Future<_i8.Debt> update(_i8.Debt? debt) =>
      (super.noSuchMethod(
            Invocation.method(#update, [debt]),
            returnValue: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(this, Invocation.method(#update, [debt])),
            ),
            returnValueForMissingStub: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(this, Invocation.method(#update, [debt])),
            ),
          )
          as _i18.Future<_i8.Debt>);

  @override
  _i18.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i8.Debt> repay(String? id, String? accountId, double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#repay, [id, accountId, amount]),
            returnValue: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(
                this,
                Invocation.method(#repay, [id, accountId, amount]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(
                this,
                Invocation.method(#repay, [id, accountId, amount]),
              ),
            ),
          )
          as _i18.Future<_i8.Debt>);

  @override
  _i18.Future<List<_i24.DebtPayment>> getPayments(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPayments, [id]),
            returnValue: _i18.Future<List<_i24.DebtPayment>>.value(
              <_i24.DebtPayment>[],
            ),
            returnValueForMissingStub:
                _i18.Future<List<_i24.DebtPayment>>.value(<_i24.DebtPayment>[]),
          )
          as _i18.Future<List<_i24.DebtPayment>>);

  @override
  _i18.Future<_i8.Debt> snooze(
    String? id,
    String? reminderDate,
    String? reminderTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#snooze, [id, reminderDate, reminderTime]),
            returnValue: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(
                this,
                Invocation.method(#snooze, [id, reminderDate, reminderTime]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i8.Debt>.value(
              _FakeDebt_6(
                this,
                Invocation.method(#snooze, [id, reminderDate, reminderTime]),
              ),
            ),
          )
          as _i18.Future<_i8.Debt>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i25.CategoryRepository {
  @override
  _i18.Stream<List<_i9.Category>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i18.Stream<List<_i9.Category>>.empty(),
            returnValueForMissingStub: _i18.Stream<List<_i9.Category>>.empty(),
          )
          as _i18.Stream<List<_i9.Category>>);

  @override
  _i18.Future<_i9.Category> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i18.Future<_i9.Category>.value(
              _FakeCategory_7(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i9.Category>.value(
              _FakeCategory_7(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i18.Future<_i9.Category>);

  @override
  _i18.Future<List<_i9.Category>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i18.Future<List<_i9.Category>>.value(
              <_i9.Category>[],
            ),
            returnValueForMissingStub: _i18.Future<List<_i9.Category>>.value(
              <_i9.Category>[],
            ),
          )
          as _i18.Future<List<_i9.Category>>);

  @override
  _i18.Future<_i9.Category> create(_i9.Category? item) =>
      (super.noSuchMethod(
            Invocation.method(#create, [item]),
            returnValue: _i18.Future<_i9.Category>.value(
              _FakeCategory_7(this, Invocation.method(#create, [item])),
            ),
            returnValueForMissingStub: _i18.Future<_i9.Category>.value(
              _FakeCategory_7(this, Invocation.method(#create, [item])),
            ),
          )
          as _i18.Future<_i9.Category>);

  @override
  _i18.Future<_i9.Category> update(_i9.Category? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i18.Future<_i9.Category>.value(
              _FakeCategory_7(this, Invocation.method(#update, [item])),
            ),
            returnValueForMissingStub: _i18.Future<_i9.Category>.value(
              _FakeCategory_7(this, Invocation.method(#update, [item])),
            ),
          )
          as _i18.Future<_i9.Category>);

  @override
  _i18.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i26.AccountRepository {
  @override
  _i18.Stream<List<_i10.Account>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i18.Stream<List<_i10.Account>>.empty(),
            returnValueForMissingStub: _i18.Stream<List<_i10.Account>>.empty(),
          )
          as _i18.Stream<List<_i10.Account>>);

  @override
  _i18.Future<_i10.Account> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i18.Future<_i10.Account>);

  @override
  _i18.Future<_i10.Account> setDefault(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#setDefault, [id]),
            returnValue: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(this, Invocation.method(#setDefault, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(this, Invocation.method(#setDefault, [id])),
            ),
          )
          as _i18.Future<_i10.Account>);

  @override
  _i18.Future<_i10.Account> adjustBalance(String? id, double? newBalance) =>
      (super.noSuchMethod(
            Invocation.method(#adjustBalance, [id, newBalance]),
            returnValue: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(
                this,
                Invocation.method(#adjustBalance, [id, newBalance]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(
                this,
                Invocation.method(#adjustBalance, [id, newBalance]),
              ),
            ),
          )
          as _i18.Future<_i10.Account>);

  @override
  _i18.Future<List<_i10.Account>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i18.Future<List<_i10.Account>>.value(
              <_i10.Account>[],
            ),
            returnValueForMissingStub: _i18.Future<List<_i10.Account>>.value(
              <_i10.Account>[],
            ),
          )
          as _i18.Future<List<_i10.Account>>);

  @override
  _i18.Future<_i10.Account> create(_i10.Account? item) =>
      (super.noSuchMethod(
            Invocation.method(#create, [item]),
            returnValue: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(this, Invocation.method(#create, [item])),
            ),
            returnValueForMissingStub: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(this, Invocation.method(#create, [item])),
            ),
          )
          as _i18.Future<_i10.Account>);

  @override
  _i18.Future<_i10.Account> update(_i10.Account? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(this, Invocation.method(#update, [item])),
            ),
            returnValueForMissingStub: _i18.Future<_i10.Account>.value(
              _FakeAccount_8(this, Invocation.method(#update, [item])),
            ),
          )
          as _i18.Future<_i10.Account>);

  @override
  _i18.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i27.ProductRepository {
  @override
  _i18.Future<List<_i11.Product>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i18.Future<List<_i11.Product>>.value(
              <_i11.Product>[],
            ),
            returnValueForMissingStub: _i18.Future<List<_i11.Product>>.value(
              <_i11.Product>[],
            ),
          )
          as _i18.Future<List<_i11.Product>>);

  @override
  _i18.Future<_i11.Product> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i18.Future<_i11.Product>);

  @override
  _i18.Future<_i11.Product> create(_i11.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#create, [product]),
            returnValue: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#create, [product])),
            ),
            returnValueForMissingStub: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#create, [product])),
            ),
          )
          as _i18.Future<_i11.Product>);

  @override
  _i18.Future<_i11.Product> update(_i11.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#update, [product]),
            returnValue: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#update, [product])),
            ),
            returnValueForMissingStub: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#update, [product])),
            ),
          )
          as _i18.Future<_i11.Product>);

  @override
  _i18.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i11.Product> sell(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#sell, [id]),
            returnValue: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#sell, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#sell, [id])),
            ),
          )
          as _i18.Future<_i11.Product>);

  @override
  _i18.Future<_i11.Product> restock(String? id, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#restock, [id, quantity]),
            returnValue: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#restock, [id, quantity])),
            ),
            returnValueForMissingStub: _i18.Future<_i11.Product>.value(
              _FakeProduct_9(this, Invocation.method(#restock, [id, quantity])),
            ),
          )
          as _i18.Future<_i11.Product>);

  @override
  _i18.Future<List<_i4.Transaction>> getSales(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSales, [id]),
            returnValue: _i18.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
            returnValueForMissingStub: _i18.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i18.Future<List<_i4.Transaction>>);
}

/// A class which mocks [ExchangeRateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRateRepository extends _i1.Mock
    implements _i28.ExchangeRateRepository {
  @override
  _i18.Future<List<_i12.ExchangeRate>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i18.Future<List<_i12.ExchangeRate>>.value(
              <_i12.ExchangeRate>[],
            ),
            returnValueForMissingStub:
                _i18.Future<List<_i12.ExchangeRate>>.value(
                  <_i12.ExchangeRate>[],
                ),
          )
          as _i18.Future<List<_i12.ExchangeRate>>);

  @override
  _i18.Future<_i12.ExchangeRate> upsert(
    _i19.Currency? baseCurrency,
    _i19.Currency? targetCurrency,
    double? rate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [baseCurrency, targetCurrency, rate]),
            returnValue: _i18.Future<_i12.ExchangeRate>.value(
              _FakeExchangeRate_10(
                this,
                Invocation.method(#upsert, [
                  baseCurrency,
                  targetCurrency,
                  rate,
                ]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i12.ExchangeRate>.value(
              _FakeExchangeRate_10(
                this,
                Invocation.method(#upsert, [
                  baseCurrency,
                  targetCurrency,
                  rate,
                ]),
              ),
            ),
          )
          as _i18.Future<_i12.ExchangeRate>);

  @override
  _i18.Future<void> delete(
    _i19.Currency? baseCurrency,
    _i19.Currency? targetCurrency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [baseCurrency, targetCurrency]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [BudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetRepository extends _i1.Mock implements _i29.BudgetRepository {
  @override
  _i18.Future<List<_i13.Budget>> getAll({bool? includeInactive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#includeInactive: includeInactive}),
            returnValue: _i18.Future<List<_i13.Budget>>.value(<_i13.Budget>[]),
            returnValueForMissingStub: _i18.Future<List<_i13.Budget>>.value(
              <_i13.Budget>[],
            ),
          )
          as _i18.Future<List<_i13.Budget>>);

  @override
  _i18.Future<_i13.Budget> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i18.Future<_i13.Budget>.value(
              _FakeBudget_11(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i18.Future<_i13.Budget>.value(
              _FakeBudget_11(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i18.Future<_i13.Budget>);

  @override
  _i18.Future<_i13.Budget> create(_i13.Budget? budget) =>
      (super.noSuchMethod(
            Invocation.method(#create, [budget]),
            returnValue: _i18.Future<_i13.Budget>.value(
              _FakeBudget_11(this, Invocation.method(#create, [budget])),
            ),
            returnValueForMissingStub: _i18.Future<_i13.Budget>.value(
              _FakeBudget_11(this, Invocation.method(#create, [budget])),
            ),
          )
          as _i18.Future<_i13.Budget>);

  @override
  _i18.Future<_i13.Budget> update(_i13.Budget? budget) =>
      (super.noSuchMethod(
            Invocation.method(#update, [budget]),
            returnValue: _i18.Future<_i13.Budget>.value(
              _FakeBudget_11(this, Invocation.method(#update, [budget])),
            ),
            returnValueForMissingStub: _i18.Future<_i13.Budget>.value(
              _FakeBudget_11(this, Invocation.method(#update, [budget])),
            ),
          )
          as _i18.Future<_i13.Budget>);

  @override
  _i18.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i14.BudgetOverview> getOverview() =>
      (super.noSuchMethod(
            Invocation.method(#getOverview, []),
            returnValue: _i18.Future<_i14.BudgetOverview>.value(
              _FakeBudgetOverview_12(this, Invocation.method(#getOverview, [])),
            ),
            returnValueForMissingStub: _i18.Future<_i14.BudgetOverview>.value(
              _FakeBudgetOverview_12(this, Invocation.method(#getOverview, [])),
            ),
          )
          as _i18.Future<_i14.BudgetOverview>);

  @override
  _i18.Future<_i15.BudgetHistory> getHistory(String? month) =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, [month]),
            returnValue: _i18.Future<_i15.BudgetHistory>.value(
              _FakeBudgetHistory_13(
                this,
                Invocation.method(#getHistory, [month]),
              ),
            ),
            returnValueForMissingStub: _i18.Future<_i15.BudgetHistory>.value(
              _FakeBudgetHistory_13(
                this,
                Invocation.method(#getHistory, [month]),
              ),
            ),
          )
          as _i18.Future<_i15.BudgetHistory>);
}

/// A class which mocks [RecurringTransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringTransactionRepository extends _i1.Mock
    implements _i30.RecurringTransactionRepository {
  @override
  _i18.Future<List<_i16.RecurringTransaction>> listActive() =>
      (super.noSuchMethod(
            Invocation.method(#listActive, []),
            returnValue: _i18.Future<List<_i16.RecurringTransaction>>.value(
              <_i16.RecurringTransaction>[],
            ),
            returnValueForMissingStub:
                _i18.Future<List<_i16.RecurringTransaction>>.value(
                  <_i16.RecurringTransaction>[],
                ),
          )
          as _i18.Future<List<_i16.RecurringTransaction>>);

  @override
  _i18.Future<void> validate(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#validate, [id]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i16.RecurringTransaction> skip(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#skip, [id]),
            returnValue: _i18.Future<_i16.RecurringTransaction>.value(
              _FakeRecurringTransaction_14(
                this,
                Invocation.method(#skip, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i18.Future<_i16.RecurringTransaction>.value(
                  _FakeRecurringTransaction_14(
                    this,
                    Invocation.method(#skip, [id]),
                  ),
                ),
          )
          as _i18.Future<_i16.RecurringTransaction>);

  @override
  _i18.Future<_i16.RecurringTransaction> deactivate(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deactivate, [id]),
            returnValue: _i18.Future<_i16.RecurringTransaction>.value(
              _FakeRecurringTransaction_14(
                this,
                Invocation.method(#deactivate, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i18.Future<_i16.RecurringTransaction>.value(
                  _FakeRecurringTransaction_14(
                    this,
                    Invocation.method(#deactivate, [id]),
                  ),
                ),
          )
          as _i18.Future<_i16.RecurringTransaction>);
}
