// Mocks generated by Mockito 5.4.6 from annotations
// in k_budget/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:k_budget/src/domain/enums/enums.dart' as _i12;
import 'package:k_budget/src/domain/models/account.dart' as _i8;
import 'package:k_budget/src/domain/models/app_config.dart' as _i2;
import 'package:k_budget/src/domain/models/category.dart' as _i7;
import 'package:k_budget/src/domain/models/debt.dart' as _i6;
import 'package:k_budget/src/domain/models/monthly_summary.dart' as _i14;
import 'package:k_budget/src/domain/models/product.dart' as _i9;
import 'package:k_budget/src/domain/models/subscription.dart' as _i5;
import 'package:k_budget/src/domain/models/transaction.dart' as _i4;
import 'package:k_budget/src/domain/repositories/account_repository.dart'
    as _i18;
import 'package:k_budget/src/domain/repositories/app_config_repository.dart'
    as _i10;
import 'package:k_budget/src/domain/repositories/auth_repository.dart' as _i3;
import 'package:k_budget/src/domain/repositories/category_repository.dart'
    as _i17;
import 'package:k_budget/src/domain/repositories/debt_repository.dart' as _i16;
import 'package:k_budget/src/domain/repositories/product_repository.dart'
    as _i19;
import 'package:k_budget/src/domain/repositories/subscription_repository.dart'
    as _i15;
import 'package:k_budget/src/domain/repositories/transaction_repository.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppConfig_0 extends _i1.SmartFake implements _i2.AppConfig {
  _FakeAppConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_2 extends _i1.SmartFake implements _i4.Transaction {
  _FakeTransaction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscription_3 extends _i1.SmartFake implements _i5.Subscription {
  _FakeSubscription_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDebt_4 extends _i1.SmartFake implements _i6.Debt {
  _FakeDebt_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategory_5 extends _i1.SmartFake implements _i7.Category {
  _FakeCategory_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccount_6 extends _i1.SmartFake implements _i8.Account {
  _FakeAccount_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProduct_7 extends _i1.SmartFake implements _i9.Product {
  _FakeProduct_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfigRepository extends _i1.Mock
    implements _i10.AppConfigRepository {
  @override
  _i11.Future<_i2.AppConfig> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i11.Future<_i2.AppConfig>.value(
              _FakeAppConfig_0(this, Invocation.method(#getConfig, [])),
            ),
            returnValueForMissingStub: _i11.Future<_i2.AppConfig>.value(
              _FakeAppConfig_0(this, Invocation.method(#getConfig, [])),
            ),
          )
          as _i11.Future<_i2.AppConfig>);

  @override
  _i11.Future<void> saveConfig(_i2.AppConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfig, [config]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> isOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#isOnboardingCompleted, []),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> setOnboardingCompleted(bool? completed) =>
      (super.noSuchMethod(
            Invocation.method(#setOnboardingCompleted, [completed]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i12.DataMode> getDataMode() =>
      (super.noSuchMethod(
            Invocation.method(#getDataMode, []),
            returnValue: _i11.Future<_i12.DataMode>.value(_i12.DataMode.local),
            returnValueForMissingStub: _i11.Future<_i12.DataMode>.value(
              _i12.DataMode.local,
            ),
          )
          as _i11.Future<_i12.DataMode>);

  @override
  _i11.Future<void> setDataMode(_i12.DataMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setDataMode, [mode]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setServerUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setServerUrl, [url]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> getServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getServerUrl, []),
            returnValue: _i11.Future<String?>.value(),
            returnValueForMissingStub: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> setTheme(_i12.AppTheme? theme) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [theme]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i12.AppTheme> getTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getTheme, []),
            returnValue: _i11.Future<_i12.AppTheme>.value(_i12.AppTheme.light),
            returnValueForMissingStub: _i11.Future<_i12.AppTheme>.value(
              _i12.AppTheme.light,
            ),
          )
          as _i11.Future<_i12.AppTheme>);

  @override
  _i11.Future<void> setTextScale(_i12.TextScale? textScale) =>
      (super.noSuchMethod(
            Invocation.method(#setTextScale, [textScale]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i12.TextScale> getTextScale() =>
      (super.noSuchMethod(
            Invocation.method(#getTextScale, []),
            returnValue: _i11.Future<_i12.TextScale>.value(
              _i12.TextScale.small,
            ),
            returnValueForMissingStub: _i11.Future<_i12.TextScale>.value(
              _i12.TextScale.small,
            ),
          )
          as _i11.Future<_i12.TextScale>);

  @override
  _i11.Future<void> setLockEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setLockEnabled, [enabled]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setLockMethod(_i12.LockMethod? method) =>
      (super.noSuchMethod(
            Invocation.method(#setLockMethod, [method]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setHashedPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setHashedPin, [pin]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i12.Feature>> getEnabledFeatures() =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledFeatures, []),
            returnValue: _i11.Future<List<_i12.Feature>>.value(
              <_i12.Feature>[],
            ),
            returnValueForMissingStub: _i11.Future<List<_i12.Feature>>.value(
              <_i12.Feature>[],
            ),
          )
          as _i11.Future<List<_i12.Feature>>);

  @override
  _i11.Future<void> setEnabledFeatures(List<_i12.Feature>? features) =>
      (super.noSuchMethod(
            Invocation.method(#setEnabledFeatures, [features]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i12.Feature>> getNavOrder() =>
      (super.noSuchMethod(
            Invocation.method(#getNavOrder, []),
            returnValue: _i11.Future<List<_i12.Feature>>.value(
              <_i12.Feature>[],
            ),
            returnValueForMissingStub: _i11.Future<List<_i12.Feature>>.value(
              <_i12.Feature>[],
            ),
          )
          as _i11.Future<List<_i12.Feature>>);

  @override
  _i11.Future<void> setNavOrder(List<_i12.Feature>? order) =>
      (super.noSuchMethod(
            Invocation.method(#setNavOrder, [order]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i11.Future<_i3.AuthResult> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i11.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i11.Future<_i3.AuthResult>);

  @override
  _i11.Future<_i3.AuthResult> register(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, name]),
            returnValue: _i11.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#register, [email, password, name]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#register, [email, password, name]),
              ),
            ),
          )
          as _i11.Future<_i3.AuthResult>);

  @override
  _i11.Future<_i3.AuthResult> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i11.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#refresh, [])),
            ),
            returnValueForMissingStub: _i11.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#refresh, [])),
            ),
          )
          as _i11.Future<_i3.AuthResult>);

  @override
  _i11.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i11.Future<String?>.value(),
            returnValueForMissingStub: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i11.Future<String?>.value(),
            returnValueForMissingStub: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> saveTokens(String? accessToken, String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [accessToken, refreshToken]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> hasValidToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasValidToken, []),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i13.TransactionRepository {
  @override
  _i11.Future<List<_i4.Transaction>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
            returnValueForMissingStub: _i11.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i11.Future<List<_i4.Transaction>>);

  @override
  _i11.Future<List<_i4.Transaction>> getByMonth(int? month, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getByMonth, [month, year]),
            returnValue: _i11.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
            returnValueForMissingStub: _i11.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i11.Future<List<_i4.Transaction>>);

  @override
  _i11.Stream<List<_i4.Transaction>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i11.Stream<List<_i4.Transaction>>.empty(),
            returnValueForMissingStub:
                _i11.Stream<List<_i4.Transaction>>.empty(),
          )
          as _i11.Stream<List<_i4.Transaction>>);

  @override
  _i11.Future<_i4.Transaction> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i4.Transaction>.value(
              _FakeTransaction_2(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i11.Future<_i4.Transaction>.value(
              _FakeTransaction_2(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i11.Future<_i4.Transaction>);

  @override
  _i11.Future<_i4.Transaction> create(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#create, [transaction]),
            returnValue: _i11.Future<_i4.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#create, [transaction]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i4.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#create, [transaction]),
              ),
            ),
          )
          as _i11.Future<_i4.Transaction>);

  @override
  _i11.Future<_i4.Transaction> update(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#update, [transaction]),
            returnValue: _i11.Future<_i4.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#update, [transaction]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i4.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#update, [transaction]),
              ),
            ),
          )
          as _i11.Future<_i4.Transaction>);

  @override
  _i11.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i14.MonthlySummary>> getMonthlySummary(
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlySummary, [month, year]),
            returnValue: _i11.Future<List<_i14.MonthlySummary>>.value(
              <_i14.MonthlySummary>[],
            ),
            returnValueForMissingStub:
                _i11.Future<List<_i14.MonthlySummary>>.value(
                  <_i14.MonthlySummary>[],
                ),
          )
          as _i11.Future<List<_i14.MonthlySummary>>);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i15.SubscriptionRepository {
  @override
  _i11.Future<List<_i5.Subscription>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i5.Subscription>>.value(
              <_i5.Subscription>[],
            ),
            returnValueForMissingStub:
                _i11.Future<List<_i5.Subscription>>.value(<_i5.Subscription>[]),
          )
          as _i11.Future<List<_i5.Subscription>>);

  @override
  _i11.Stream<List<_i5.Subscription>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i11.Stream<List<_i5.Subscription>>.empty(),
            returnValueForMissingStub:
                _i11.Stream<List<_i5.Subscription>>.empty(),
          )
          as _i11.Stream<List<_i5.Subscription>>);

  @override
  _i11.Future<_i5.Subscription> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i5.Subscription>.value(
              _FakeSubscription_3(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Subscription>.value(
              _FakeSubscription_3(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i11.Future<_i5.Subscription>);

  @override
  _i11.Future<_i5.Subscription> create(_i5.Subscription? subscription) =>
      (super.noSuchMethod(
            Invocation.method(#create, [subscription]),
            returnValue: _i11.Future<_i5.Subscription>.value(
              _FakeSubscription_3(
                this,
                Invocation.method(#create, [subscription]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Subscription>.value(
              _FakeSubscription_3(
                this,
                Invocation.method(#create, [subscription]),
              ),
            ),
          )
          as _i11.Future<_i5.Subscription>);

  @override
  _i11.Future<_i5.Subscription> update(_i5.Subscription? subscription) =>
      (super.noSuchMethod(
            Invocation.method(#update, [subscription]),
            returnValue: _i11.Future<_i5.Subscription>.value(
              _FakeSubscription_3(
                this,
                Invocation.method(#update, [subscription]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.Subscription>.value(
              _FakeSubscription_3(
                this,
                Invocation.method(#update, [subscription]),
              ),
            ),
          )
          as _i11.Future<_i5.Subscription>);

  @override
  _i11.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [DebtRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDebtRepository extends _i1.Mock implements _i16.DebtRepository {
  @override
  _i11.Future<List<_i6.Debt>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i6.Debt>>.value(<_i6.Debt>[]),
            returnValueForMissingStub: _i11.Future<List<_i6.Debt>>.value(
              <_i6.Debt>[],
            ),
          )
          as _i11.Future<List<_i6.Debt>>);

  @override
  _i11.Stream<List<_i6.Debt>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i11.Stream<List<_i6.Debt>>.empty(),
            returnValueForMissingStub: _i11.Stream<List<_i6.Debt>>.empty(),
          )
          as _i11.Stream<List<_i6.Debt>>);

  @override
  _i11.Future<_i6.Debt> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i6.Debt>.value(
              _FakeDebt_4(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Debt>.value(
              _FakeDebt_4(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i11.Future<_i6.Debt>);

  @override
  _i11.Future<_i6.Debt> create(_i6.Debt? debt) =>
      (super.noSuchMethod(
            Invocation.method(#create, [debt]),
            returnValue: _i11.Future<_i6.Debt>.value(
              _FakeDebt_4(this, Invocation.method(#create, [debt])),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Debt>.value(
              _FakeDebt_4(this, Invocation.method(#create, [debt])),
            ),
          )
          as _i11.Future<_i6.Debt>);

  @override
  _i11.Future<_i6.Debt> update(_i6.Debt? debt) =>
      (super.noSuchMethod(
            Invocation.method(#update, [debt]),
            returnValue: _i11.Future<_i6.Debt>.value(
              _FakeDebt_4(this, Invocation.method(#update, [debt])),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Debt>.value(
              _FakeDebt_4(this, Invocation.method(#update, [debt])),
            ),
          )
          as _i11.Future<_i6.Debt>);

  @override
  _i11.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i17.CategoryRepository {
  @override
  _i11.Stream<List<_i7.Category>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i11.Stream<List<_i7.Category>>.empty(),
            returnValueForMissingStub: _i11.Stream<List<_i7.Category>>.empty(),
          )
          as _i11.Stream<List<_i7.Category>>);

  @override
  _i11.Future<_i7.Category> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i7.Category>.value(
              _FakeCategory_5(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i11.Future<_i7.Category>.value(
              _FakeCategory_5(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i11.Future<_i7.Category>);

  @override
  _i11.Future<List<_i7.Category>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i7.Category>>.value(
              <_i7.Category>[],
            ),
            returnValueForMissingStub: _i11.Future<List<_i7.Category>>.value(
              <_i7.Category>[],
            ),
          )
          as _i11.Future<List<_i7.Category>>);

  @override
  _i11.Future<_i7.Category> create(_i7.Category? item) =>
      (super.noSuchMethod(
            Invocation.method(#create, [item]),
            returnValue: _i11.Future<_i7.Category>.value(
              _FakeCategory_5(this, Invocation.method(#create, [item])),
            ),
            returnValueForMissingStub: _i11.Future<_i7.Category>.value(
              _FakeCategory_5(this, Invocation.method(#create, [item])),
            ),
          )
          as _i11.Future<_i7.Category>);

  @override
  _i11.Future<_i7.Category> update(_i7.Category? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i11.Future<_i7.Category>.value(
              _FakeCategory_5(this, Invocation.method(#update, [item])),
            ),
            returnValueForMissingStub: _i11.Future<_i7.Category>.value(
              _FakeCategory_5(this, Invocation.method(#update, [item])),
            ),
          )
          as _i11.Future<_i7.Category>);

  @override
  _i11.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i18.AccountRepository {
  @override
  _i11.Stream<List<_i8.Account>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i11.Stream<List<_i8.Account>>.empty(),
            returnValueForMissingStub: _i11.Stream<List<_i8.Account>>.empty(),
          )
          as _i11.Stream<List<_i8.Account>>);

  @override
  _i11.Future<_i8.Account> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i11.Future<_i8.Account>);

  @override
  _i11.Future<_i8.Account> setDefault(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#setDefault, [id]),
            returnValue: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(this, Invocation.method(#setDefault, [id])),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(this, Invocation.method(#setDefault, [id])),
            ),
          )
          as _i11.Future<_i8.Account>);

  @override
  _i11.Future<_i8.Account> adjustBalance(String? id, double? newBalance) =>
      (super.noSuchMethod(
            Invocation.method(#adjustBalance, [id, newBalance]),
            returnValue: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(
                this,
                Invocation.method(#adjustBalance, [id, newBalance]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(
                this,
                Invocation.method(#adjustBalance, [id, newBalance]),
              ),
            ),
          )
          as _i11.Future<_i8.Account>);

  @override
  _i11.Future<List<_i8.Account>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i8.Account>>.value(<_i8.Account>[]),
            returnValueForMissingStub: _i11.Future<List<_i8.Account>>.value(
              <_i8.Account>[],
            ),
          )
          as _i11.Future<List<_i8.Account>>);

  @override
  _i11.Future<_i8.Account> create(_i8.Account? item) =>
      (super.noSuchMethod(
            Invocation.method(#create, [item]),
            returnValue: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(this, Invocation.method(#create, [item])),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(this, Invocation.method(#create, [item])),
            ),
          )
          as _i11.Future<_i8.Account>);

  @override
  _i11.Future<_i8.Account> update(_i8.Account? item) =>
      (super.noSuchMethod(
            Invocation.method(#update, [item]),
            returnValue: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(this, Invocation.method(#update, [item])),
            ),
            returnValueForMissingStub: _i11.Future<_i8.Account>.value(
              _FakeAccount_6(this, Invocation.method(#update, [item])),
            ),
          )
          as _i11.Future<_i8.Account>);

  @override
  _i11.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i19.ProductRepository {
  @override
  _i11.Future<List<_i9.Product>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i9.Product>>.value(<_i9.Product>[]),
            returnValueForMissingStub: _i11.Future<List<_i9.Product>>.value(
              <_i9.Product>[],
            ),
          )
          as _i11.Future<List<_i9.Product>>);

  @override
  _i11.Future<_i9.Product> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#getById, [id])),
            ),
            returnValueForMissingStub: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i11.Future<_i9.Product>);

  @override
  _i11.Future<_i9.Product> create(_i9.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#create, [product]),
            returnValue: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#create, [product])),
            ),
            returnValueForMissingStub: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#create, [product])),
            ),
          )
          as _i11.Future<_i9.Product>);

  @override
  _i11.Future<_i9.Product> update(_i9.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#update, [product]),
            returnValue: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#update, [product])),
            ),
            returnValueForMissingStub: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#update, [product])),
            ),
          )
          as _i11.Future<_i9.Product>);

  @override
  _i11.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i9.Product> sell(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#sell, [id]),
            returnValue: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#sell, [id])),
            ),
            returnValueForMissingStub: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#sell, [id])),
            ),
          )
          as _i11.Future<_i9.Product>);

  @override
  _i11.Future<_i9.Product> restock(String? id, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#restock, [id, quantity]),
            returnValue: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#restock, [id, quantity])),
            ),
            returnValueForMissingStub: _i11.Future<_i9.Product>.value(
              _FakeProduct_7(this, Invocation.method(#restock, [id, quantity])),
            ),
          )
          as _i11.Future<_i9.Product>);

  @override
  _i11.Future<List<_i4.Transaction>> getSales(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSales, [id]),
            returnValue: _i11.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
            returnValueForMissingStub: _i11.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i11.Future<List<_i4.Transaction>>);
}
